FROM dashbook/airbyte-java-source-builder:latest AS build
RUN gradle --no-daemon :airbyte-integrations:connectors:source-postgres:assemble
RUN tar -xvf /home/gradle/src/airbyte-integrations/connectors/source-postgres/build/distributions/source-postgres*.tar --strip-components=1 

FROM dashbook/destination-iceberg:java-sql

WORKDIR /airbyte

ENV AIRBYTE_SOURCE=source-postgres

COPY --from=build /home/gradle/src/lib /airbyte/lib
COPY --from=build /home/gradle/src/bin /airbyte/bin
COPY --from=build /home/gradle/src/sync-java.sh /airbyte/bin/sync.sh

ENTRYPOINT ["/bin/bash","-c","/airbyte/bin/sync.sh"]


