name: source-python

on:
  push:
    branches: ["master"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-google-analytics-v4/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-google-analytics-v4:sql
          cache-from: type=registry,ref=dashbook/source-google-analytics-v4:sql
          cache-to: type=inline

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-s3/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-s3:sql
          cache-from: type=registry,ref=dashbook/source-s3:sql
          cache-to: type=inline

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-facebook-marketing/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-facebook-marketing:sql
          cache-from: type=registry,ref=dashbook/source-facebook-marketing:sql
          cache-to: type=inline

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-google-sheets/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-google-sheets:sql
          cache-from: type=registry,ref=dashbook/source-google-sheets:sql
          cache-to: type=inline

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-hubspot/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-hubspot:sql
          cache-from: type=registry,ref=dashbook/source-hubspot:sql
          cache-to: type=inline

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-salesforce/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-salesforce:sql
          cache-from: type=registry,ref=dashbook/source-salesforce:sql
          cache-to: type=inline

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-openweather/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-openweather:sql
          cache-from: type=registry,ref=dashbook/source-openweather:sql
          cache-to: type=inline
