name: source-java

on:
    workflow_run:
        workflows: ['base-java']
        types: [completed]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-postgres/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-postgres:sql
          cache-from: type=registry,ref=dashbook/source-postgres:sql
          cache-to: type=inline
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-mysql/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-mysql:sql
          cache-from: type=registry,ref=dashbook/source-mysql:sql
          cache-to: type=inline
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-kafka/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-kafka:sql
          cache-from: type=registry,ref=dashbook/source-kafka:sql
          cache-to: type=inline
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-mongodb-v2/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-mongodb-v2:sql
          cache-from: type=registry,ref=dashbook/source-mongodb-v2:sql
          cache-to: type=inline
