name: source-python

on:
  push:
    branches: ["master"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:airbyte-integrations/connectors/source-google-analytics-v4/"
          file: Dockerfile_sql
          push: true
          tags: dashbook/source-google-analytics-v4:sql
          cache-from: type=registry,ref=dashbook/source-google-analytics-v4:sql
          cache-to: type=inline
